### ISSUE TITLE
UI development using Storyboards

### ISSUE THREAD

**Issue by webframp** [MobileOrg/mobileorg#101]
The question has come up in discussion about using iOS Storyboards for UI design. Currently the app makes little to no use of storyboards, with the exception of the newly added Launch screen in the development codebase. 

Storyboards have been around long enough to make their usage now generally standard I think. Since they are often promoted as the right direction for future app development we should get input from contributors.

I am generally in favor of Storyboards, provided we do not create one massive storyboard to rule them all. I think it makes sense to have the Storyboard tell a story, logically grouping view controllers and behaviors but not trying to cover every single view.

What other Pros/Cons do you see when compared with just code driven UI or existing .xib files?

**Comment by webframp** [comment]
Found a decent article for reference: [Storyboards vs. NIBs vs. Custom Code](https://www.toptal.com/ios/ios-user-interfaces-storyboards-vs-nibs-vs-custom-code)

**Comment by mgmart** [comment]
I definitely favour Storyboard.

The linked article covers all aspects. One addition: since Xcode 7 with Storyboard refrences there is an additional feature for organising Storyboards.

**Comment by mgmart** [comment]
v2 will use storyboards
