### ISSUE TITLE
Swift vs Objective-c

### ISSUE THREAD

**Issue by webframp** [MobileOrg/mobileorg#102]
This issue is for discussion of a few things related to language choice:

- How do we feel about preferring one or the other for new code? 
- What effort should we put towards refactoring areas of the code from one to the other and why?
- How do we communicate this preference to possible contributors?

**Comment by mgmart** [comment]
If we agree on the fact that the proposed changes to UI/UX would lead to a fresh start regarding to the codebase, I would say it might be sufficient to favour Swift for the old codebase but still allow Objective C contributions.

The new codebase could then be Swift only. And there would be no need for refactoring the old codebase.

**Comment by mgmart** [comment]
v2 will be Swift only
