### ISSUE TITLE
Create a Share Sheet

### ISSUE THREAD

**Issue by ckruse** [MobileOrg/mobileorg#106]
It would really be nice to have a share sheet which creates a new capture for the shared content.

**Comment by mgmart** [comment]
Would like to have that too. Do you have any particular use-cases (apps) in mind? 
I would like to use it for Safari links and Evernote (as a link to a note).

**Comment by ckruse** [comment]
For my use cases that would be Mail, Twitter, Tweetbot, Reeder and Reddit (the official client). :-)

**Comment by webframp** [comment]
My common use case is also URLs for this, sometimes quotes from articles. 

Functionally would this share sheet just capture to a dedicated file to allow the user to refile later? Possibly configurable in MobileOrg settings?

**Comment by ckruse** [comment]
Does the Org-Sync-Protocol allow to capture to dedicated files? I thougt you can just add captures, independent of the file?

**Comment by mgmart** [comment]
I had a look into the App Extension API (which I think is needed for receiving shared content) and it seems rather difficult to implement that with the current codebase. First of all we would need the to duplicate the necessary Core Data code into the App Extension or refactor it to an embedded Framework which then could be used by the main app and the extension.
As we could foresee that in the architecture for v2 I would suppose to implement the share extension there. 
@ckruse (end everyone else 😄)there is an [ongoing discussion about a new version of MobileOrg](https://paper.dropbox.com/doc/The-Incubator-dznQbK5Su2BNAXZl48iPG) which you might like to join.
It's also my understanding that every new content must go through captures.

**Comment by mgmart** [comment]
@brhumpe in #100
> Or if triggering from the share sheet, then a menu might open asking where to file the item, similar to OneNote

I do not know OneNote but I could imagine the menu right away in the share-sheet.

**Comment by mgmart** [comment]
Collected in requirements
