### ISSUE TITLE
Refiling functionality

### ISSUE THREAD

**Issue by d12frosted** [MobileOrg/mobileorg#109]
I think it would be great to have a functionality to refile items in MobileOrg.

**Comment by mgmart** [comment]
Put this to 'v2' as a suggestion. Can be relabelled at any time.

**Comment by mgmart** [comment]
How does handle org-mode document related todo keywords if item is refiled?

How should do we handle it if the answer is that it does not?

**Comment by mgmart** [comment]
Would org-mobile.el support refiling?

**Comment by d12frosted** [comment]
I haven't tried it, but I think it refiles as is, without any changes. Why should it? 😸

**Comment by mgmart** [comment]
I'm still under the impression of #97. :feelsgood:

**Comment by mgmart** [comment]
Collected in Requirements
