### ISSUE TITLE
App Badge is not shown

### ISSUE THREAD

**Issue by mgmart** [MobileOrg/mobileorg#116]
To reproduce: 
- Switch on `Show App Badge` in Settings
- Make edits 
- Verify the amount of changes by adding the badge values of `Outlines`and `Capture` tabbar icons

Expected outcome:
- There is an app badge which shows the correct amount of edits

Real outcome:
- No app badge at all

**Comment by mgmart** [comment]
For the app badge to work in iOS 8+ you have to ask for permission to send notifications.
> If your app displays alerts, play sounds, or badges its icon, you must call this method during your launch cycle to request permission to alert the user in these ways. **(You must also make this request if you want to set the applicationIconBadgeNumber property directly.)** ...

There are two possible solutions:
- Asking the for permission to send notification and not sending any
- Removing the app badge feature

**Comment by webframp** [comment]
I'm fine with requesting the permissions if needed of course, but is the app badge even a useful feature for people as currently implemented?

**Comment by mgmart** [comment]
I'm not happy with asking for permission to send notifications because this would make some users expecting notifications from MobileOrg.

We could flag the switch in settings with a warning sign and description what the App Badge does. 
Permission would only be asked if Switch is on.
