### ISSUE TITLE
Does it make sense to use git or nothing at all as an alternative to org-mobile.el

### ISSUE THREAD

**Issue by mgmart** [MobileOrg/mobileorg#120]
org-mobile.el is a fantastic piece of code as it allows to sync org-files without producing any kind of conflicts. Nevertheless for many users it's annoying to remember every time to push/pull when changing devices. As an alternative MobileOrg could work directly with org-files stored in iCloud/Dropbox/... . Or, as another alternative as many users use Org-mode with git, MobileOrg could use git too.

Under particular circumstances both alternatives would lead to sync-conflicts which would have been to be resolved in MobileOrg.
Although there are existing bug reports for org-mobile.el here (#68 & #97), it seems not many are concerned about them. 

What would be the best way to handle sync in the future? Are there ways to circumvent conflicts? Are there easy ways to resolve occurring conflicts within MobileOrg? How could we could get a grip on org-mobile.el to resolve current or future issues?

**Comment by abradd** [comment]
I agree that working with org files directly is very useful. Any offline work has a risk of sync-conflicts, Dropbox just creates a copy of the file that is conflicted. For Dropbox users this would at least preserve any conflicted data, may not help webDAV users. I’m not sure how applications like OmniFocus handle this, but they might provide some insight at least in the front-end interface for conflict resolution. How does org-mobile.el currently avoid conflicts? For example, if I push todos to MobileOrg, then update my todos on my laptop, then change the same todos on MobileOrg in a different way, then pull the changes from MobileOrg. Does it just look at the checksum and take the most recent version?

Using a git backend could be helpful in this sense as a sync-conflict is basically a merge-conflict making resolution reasonable on a laptop etc. Not sure how easy these conflicts would be to resolve on mobile. Probably depends on the complexity of the diff.

I imagine the only way to avoid sync-conflicts when working directly with org files is to enforce an online-only workflow which seems like a bad idea.

**Comment by mgmart** [comment]
>  I’m not sure how applications like OmniFocus handle this

I suppose they use Core Data

> I imagine the only way to avoid sync-conflicts when working directly with org files is to enforce an online-only workflow which seems like a bad idea.

Maybe this could stand as a third alternative in this discussion.

- If phone is online, work takes place on the org-files
- If phone is offline, every change is stored separately
- If phones comes back online
   1. read org-files
   2. merge changes 
this could be done on the phone easier* as with file-only merge if we suppose that Core Data is still used as storage in the future

*Don't know if that is really true 🦄

**Comment by webframp** [comment]
Some comments from the org-mode mailing list thread:

_Alan:_
> I use git, and would very much like to be able to use that as a backend to synchronize (I'm trying to move away from dropbox)

_Eric:_
> The inability to use git directly was the main reason I didn't end up using MobileOrg.

_Anssi:_
> since initiating manual sync from Emacs seemed mandatory I just didn't get much use out
of MobileOrg. So whatever you want to provide, make sure sync is automatic. And
preferably supporting private sync options too.

Some suggested an emacs config to auto sync such as:

_Gijs:_
```scheme
(run-at-time "10:15" 86400 'org-mobile-push)
```

_Karl:_
> using WebDav for syncing with Android. I will switch from
WebDav to SyncThing since it turned out to be a very neat and easy
to use sync method with enhanced privacy. Apple decided not to support tools like SyncThing for political reasons, so no luck for iOS here.

**Comment by mgmart** [comment]
v1.7 is nearly ready and focus will now tracked more to v2.
As we got no answers how to implement an alternative approach I would suggest:
- v2 will take the mobile-org.el approach
- software architecture must foresee the future implementation of an alternative snyc-mechanism either by
  - implementing sync in embedded frameworks, or
  - using a module approach.
