### ISSUE TITLE
Removal of Autocapture

### ISSUE THREAD

**Issue by mgmart** [MobileOrg/mobileorg#122]
I would like to remove the 'Autocapture' (#21) functionality

It might be useful on iOS without multitasking switching, but on nowaday-devices it might only confuse the user (#65). 

@vermiculus: what do you think about it?

**Comment by vermiculus** [comment]
What's wrong with it? It does exactly what it's supposed to do…

If it's on by default, it might be a good thing to turn *off* by default.

**Comment by mgmart** [comment]
My concern is that it is triggered also by task switching and therefore nobody would use it. Having the switch, leads some users to use it and then forget about it (#65 as an example). This could potentially lead to a bad acceptance of the app.

But if we have users still using autocapture, we could mark the setting with a big red exclamation mark and some explanation what it does.

**Comment by vermiculus** [comment]
> **it is triggered also by task switching** and therefore nobody would use it

Can you be a bit more explicit about what the problem is? AFAIK, **that** is almost exactly what's designed. It's intended for folks who use MobileOrg purely as a task-capture tool (such as myself).

I have no problem removing the feature if there's a good reason to do so, but I want to make sure this isn't throwing the baby out with the bathwater, so to speak.

**Comment by mgmart** [comment]
> It's intended for folks who use MobileOrg purely as a task-capture tool (such as myself).

Could you please talk a bit of your usage in #100? I'm sure this would help us very much.

I would not call it a problem. It's rather an inconvenience. Thinking of it, it might be a solution to use the capture button in the tabbar for triggering a new note if the user is already in the capture screen.

[In the video I tried to visualise the inconvenience.](https://dl.dropboxusercontent.com/u/36821439/Task%20Switching.mov)
It's a bit long but it is already the fifth attempt. Sorry for that.

**Comment by vermiculus** [comment]
> Could you please talk a bit of your usage

I'll make a note, but it'll be small

> In the video I tried to visualise the inconvenience.

Ah! Yes, that's definitely annoying and not the intended behavior. On the theme of throwing the baby out with the bathwater, the *bathwater* seems to be 'in-progress captures are interrupted'. *That's* the bug – not autocapture in general 😄

If MobileOrg is/was already in the process of writing a note, then we shouldn't create a new one. I'd expect users like me would use `Done` or `< Capture` when completing the note.

> Thinking of it, it might be a solution to use the capture button in the tabbar for triggering a new note if the user is already in the capture screen.

I'd recommend against this – the tabbar is a fundamental navigational component and should behave the same way irrespective of where you are in the application. A `+` button in the upper right would be more idiomatic.

**Comment by webframp** [comment]
I don't think this behavior needs to be removed, but possibly refactored or more clearly described in the settings. It's not default behavior so I don't see it being too confusing to users. 

As @vermiculus points out, he does use it. There may be others. 

One app that I have used with similar behavior is [drafts from agile tortoise](http://agiletortoise.com/drafts/). It's default setting creates a new note when opening the app and is configurable in app settings how long the delay is between launching app that creates a new note or opens the last one

**Comment by vermiculus** [comment]
> configurable in app settings how long the delay is between launching app that creates a new note or opens the last one

Such a delay would handily address the problem use case here as well (and sounds exactly like a suggestion noted in the original PR).

**Comment by mgmart** [comment]
> I'd recommend against this – the tabbar is a fundamental navigational component and should behave the same way irrespective of where you are in the application. A + button in the upper right (or somewhere) would be more idiomatic.

Good point

I would propose a warning in the settings for 1.7 as a solution, in the case that nobody volunteers to do the refactoring 😉

**Comment by webframp** [comment]
Totally open to the idea of UX improvements with the feature, but since we know it's used lets not plan to remove this but discuss improvements as needed once we get more details from #100 maybe?

**Comment by mgmart** [comment]
No answers without question. Thought it would be sufficient to flag the topic as a question. 😉 

I'm totally fine with keeping it. I still doubt there are users still using this feature, as @vermiculus points out he is not using MobileOrg anymore. But as you said, maybe there are others.

With our new storyboard (thanks @jamie-conlon) we can now easily put a nice warning sign to the switch in the settings screen. That would help with my concerns regarding user acceptance and (AppStore) rating.

**Comment by webframp** [comment]
Definitely worth asking the questions so we can improve things 👍

**Comment by manmatteo** [comment]
I accidentally enabled AutoCapture mode and couldn't understand what was going on with MobileOrg. After much googling I reached this issue and deactivated it.
I suggest also based on the above discussion that it either be removed or renamed to a more convenient name (such as "Always open in Capture Mode").
