### ISSUE TITLE
Icons used within the app are not retina.

### ISSUE THREAD

**Issue by mgmart** [MobileOrg/mobileorg#127]
Icons in 'Document View' and the tabbar are not retina. Looking ugly on modern devices.

There are some free icon sets available. 
I suppose icons from http://www.flaticon.com could be used within the project, but not sure about it.

I could help with converting svg to x1, x2, x3 if necessary.

**Comment by mgmart** [comment]
if #126 is done there would be only the tabbar icons left

**Comment by webframp** [comment]
Since @jamie-conlon has a good idea for the Doc View enhancements it makes sense to do this one after #126

**Comment by mgmart** [comment]
For the time being the current icons must be sufficient. And they are not looking too bad after the latest changes to screen size.

After #126 the screen could be omitted.
