### ISSUE TITLE
Error downloading checksums

### ISSUE THREAD

**Issue by webframp** [MobileOrg/mobileorg#128]
Reported issue from TestFlight testing
![0](https://cloud.githubusercontent.com/assets/774378/21857000/e962a2e6-d7f1-11e6-8d84-aeb3b711ca21.png)

### Device Information
```
App Information:
App Name: MobileOrg
App Version: 1.7.1 (1)
Installed App Version: 1.7.1 (1)

Device Information:
Device: iPad6,7
iOS Version: 10.2
Language: en (English)
Carrier: N/A
Timezone: EST
Architecture: N/A
Connection Status: WiFi
Paired Apple Watch: N/A
device_information.txt
Displaying image1.PNG.
```

Reported by @jamiesmy

**Comment by mgmart** [comment]
Is there a checksums.dat present?

**Comment by webframp** [comment]
There may not be, but the user experience from this error isn't great

**Comment by mgmart** [comment]
Agree. But it would be a different kind of bug wether the file is present or not.

**Comment by mgmart** [comment]
Seems to be an old one :( #32
