### ISSUE TITLE
1.7.1 Beta: Error syncing changes (over WebDAV)

### ISSUE THREAD

**Issue by stormlash** [MobileOrg/mobileorg#133]
I've installed the Beta of 1.7.1 through TestFlight, but when trying to sync over WebDav I receive the following message:

> **Error syncing changes**
An error was encountered while attempting to fetch mobileorg.org from the server. The error was:
Failure

I've reverted to 1.6.1 from the app store and am able to sync fine with the same settings.

The WebDAV server is reached over HTTPS on port 5006, with a somewhat long file path and password.

**Comment by webframp** [comment]
Thanks for reporting!

**Comment by webframp** [comment]
@mgmart what do you think, related to #119 in any way?

**Comment by jamie-conlon** [comment]
It could be something related to the settings screen update I pushed. I didn't test webDAV either. I'll have a look to see if I've messed anything up.

**Comment by jamie-conlon** [comment]
So it looks like the URL validation did not survive the conversion to swift. It compiles fine but I never tested it... 
Will have a fix soon.
