### ISSUE TITLE
Beta 1.7.1: Long WebDAV URL does not display properly

### ISSUE THREAD

**Issue by stormlash** [MobileOrg/mobileorg#134]
The URL I have specified in my WebDAV configuration is 71 characters long, and does not display properly in the settings panel.  The last 32 characters are readable, but the preceding ones print over the text "URL" and then run off the left side of the screen. See screenshot for an example.

At the very least, the "URL" text should not be overwritten - but it would be really nice if the input field would stretch vertically so as to display the entire URL.

![fullsizerender](https://cloud.githubusercontent.com/assets/2788160/21874289/2f0f64b4-d842-11e6-8eef-caac4b0d62ed.jpg)

**Comment by webframp** [comment]
Seems related to #133
