### ISSUE TITLE
Accessing existing capture templates

### ISSUE THREAD

**Issue by abradd** [MobileOrg/mobileorg#140]
Would be nice to have access to capture templates defined in our .emacs (or elsewhere) inside MobileOrg.

**Comment by mgmart** [comment]
could be triggered by: 

- [Widgets](https://developer.apple.com/ios/human-interface-guidelines/extensions/widgets/)
- [Sharing](https://developer.apple.com/ios/human-interface-guidelines/extensions/sharing-and-actions/)
- `New Note` within the App

=> #106

**Comment by mgmart** [comment]
Collected in Requirements

**Comment by sk8ingdom** [comment]
I'd be very interested in this capability, is it planed for the 2.0 release?

**Comment by mgmart** [comment]
@sk8ingdom, at the moment it's covered in the [requirement document](https://github.com/MobileOrg/mobileorg.next/blob/specification/docs/MobileOrgv2.org#capture), before it could get planned we have to get an idea how to implement this.

If you like you could give some input on this (or other) requirement by providing in the [issues section of v2](https://github.com/MobileOrg/mobileorg.next/issues)

**Comment by sk8ingdom** [comment]
@mgmart thanks for the update! I'll be sure to look through the issues.
