### ISSUE TITLE
Representative Testfiles

### ISSUE THREAD

**Issue by mgmart** [MobileOrg/mobileorg#141]
To be able to test during development and beta-test.

- Should be pretty complex.
- Should be shared with developers, testers and users
- Should include org-mode configuration
   (as some defects could occur on emacs, e.g. #97)

**Comment by webframp** [comment]
How about we just use some of the same ones from here: http://orgmode.org/cgit.cgi/org-mode.git/tree/testing/examples ?

**Comment by mgmart** [comment]
> How about we just use some of the same ones from here: http://orgmode.org/cgit.cgi/org-mode.git/tree/testing/examples ?

I suppose those are not suitable for our needs. They seem to focus mainly on org-babel.

Testfiles for MobileOrg should include:
- priorities
- tags
- todo and done keywords
- many heading levels
- agenda files like they are generated by org-mobile.el
- ...
