### ISSUE TITLE
Orgzly

### ISSUE THREAD

**Issue by gburch** [MobileOrg/mobileorg#142]
Would like to start a discussion about considerations of combining or collaborating with [Orgzly](http://www.orgzly.com/). They do have an entirely different approach of supporting org files directly and in my brief testing on Android it seems to work fine. They do not have an iOS version. 

There is a large demand for being able to work with org files on mobile but a small number of developers focused on it. Seems combining efforts if both strategy and business reasons align. 

Some questions, potentially only for my benefit, to get us started.

1. Why was syncing and exporting chosen? Is this a legacy reason that hasn't been addressed? Is it fear of corruption? For customization that might usually not be included in plain text files such as TODO tags?
2. Why did this project lose any traction for years? Too few developers to pick up when some got busy? 
3. What is the ultimate goal of MobileOrg? Just TODO or as much full org support as possible?

PS. Orgzly website says it is not FOSS but it may one day be, linking to their [github repository](https://github.com/orgzly/org-java). However in that repository there is a GNU General Public License matching that of this project. Repository was created 2 months ago and at the time of this writing the last commit was Dec 9th 2016, so recently.

**Comment by gburch** [comment]
I will close this to focus valuable feedback into that ticket. For whatever reason that ticket didn't have a title that jumped out at me as a similar issue.

**Comment by webframp** [comment]
Thanks for participating @gburch ! Your input will help make MobileOrg better.
