### ISSUE TITLE
Heading level skips (again ...)

### ISSUE THREAD

**Issue by jonathanwilner** [MobileOrg/mobileorg#163]
I built and installed from HEAD onto my 7Plus. It's working great to sync and use MobileOrg when in the emulator, but I am crashing on the real device when attempting to sync a relatively large org-file. It crashes before finishing transfering all the agenda files, leaving me with the right list of files from index.org, but each of them are apparently empty.

**Comment by mgmart** [comment]
Could you run the app from xCode on the device and provide detailed information on the crash?

**Comment by webframp** [comment]
Thanks for reporting this @jonathanwilner. 

I definitely haven't seen this any betas in my testing and i personally use the Dropbox integration. Please let us know what we can do to reproduce, interested to see what the issue is.

**Comment by jonathanwilner** [comment]
I'm not an IOS developer or XCode expert, so I might be doing something wrong, but I am not getting any debug info or crash logging on the device, it just basically stops. I've tried to step through the debugger, but not catching anything yet. It's always on the largest file, but even when I've cut it down to a small size (just one year of notes + tasks), still it happens.

I am NOT getting this problem when running from Xcode on the iPad Pro, running 10.2 (14C92) instead of 10.2.1 on the 7Plus. Everything works fine, though the information in the org file is oddly cut off - it grabs like 6 months of a years notes (a year is a top level heading), instead of the whole thing. No problem with tasks/agenda though.

**Comment by mgmart** [comment]
If you run the app from xCode and it crashes then there must be some stack trace visible in xCode. Most likely a code line is marked red. Also in the left sidepane (6th tab) there should be some information about the current state.

**Comment by jonathanwilner** [comment]
@mgmart is it possible that iOS doesn't think it's a crash, but just the program exiting? Honestly, I could post a screen capture / video that shows it just stopping with no info in xCode.

**Comment by mgmart** [comment]
Thought the app was crashing because you wrote it was crashing :smile:

I assume a problem with the amount of entries. 
What I understood is, that you have many entries in the file. Is the following assumption correct?

- 6 years
  - 12 month per year
    - about 30 day entries per month
       - some subentries per day

That would be 2000 - 3000 lines with stars at the beginning?

Can you tell how big the size of the file is?

**Comment by abradd** [comment]
As a point of reference, my largest file has 1231 headlines (with stars), just over 10,000 lines (with and without stars) and is 476 kB and this is loaded fine. I even pulled this entire file up in Document View and it worked (though it took a while to populate). My file uses date-tree format, but I separate each year into its own file.

I checked headline count with:

    (1- (length (org-map-entries nil nil 'file)))

**Comment by mgmart** [comment]
@jonathanwilner Any news on this?

**Comment by jonathanwilner** [comment]
@mgmart : I haven't tried XCode again, but I have been able to get MobileOrg to complete syncing on the iPhone, by cutting back and manually editing the org file. What I found is that ANY gaps or sequence skips in the order of headlines breaks the viewer on any device. The difference for me is that the emulator will sync the files and sort of work, same as the iPad Pro, whereas the iPhone will exit before finalizing the sync when it hits the file with the skip order.

Example that seems to cause the problem:

* A
**B
**** D

My original organizer.org file is 199K, 3695 lines. I am not sure exactly how to use the lisp code above to check for headlines using the API.  :-)

**Comment by mgmart** [comment]
> gaps or sequence skips in the order of headlines

Great, that's something we must be able to reproduce in some way. It's a shame, though. We have tackled this particular scenario in #62. 

>  I am not sure exactly how to use the lisp code above to check for headlines using the API. :-)

Just for reference, as it seems not to be the amount of headlines which is causing this particular problem.
Paste the code in a separate line at the end of your org-file. Position the cursor after the last parenthesis and press `C-x C-e` and you should see the result in the mini buffer.

This works because emacs is not an editor 😄

**Comment by jonathanwilner** [comment]
😁 - exactly! I did try to execute the code in the region first, but
something must be off. Trying again now.

**Comment by jonathanwilner** [comment]
The result appears to be 2509 in the larger file.

**Comment by mgmart** [comment]
It seems, that the content is not cut off. Instead it is wrongly indented

* Headline 1
  ** Subsection 2
  **** Subsection 4
* Headline 2

In my test scenario `Headline 2` is on the same level as `Subsection 4` in MobileOrg
