### ISSUE TITLE
Make the app split-able to allow side-by-side use on supported devices

### ISSUE THREAD

**Issue by webframp** [MobileOrg/mobileorg#168]
User suggested feature, research what's required. If work is minor, could be incorporated into v1 release.

**Comment by mgmart** [comment]
What channel did the user use?

Don't know exactly but I'm pretty sure that auto-layout is needed to support split-view. If so, then that would be not so easy for v1.

**Comment by webframp** [comment]
Emailed privately, if it's v2 that's fine

**Comment by mgmart** [comment]
Just found out that it's quite easy to implement.
