### ISSUE TITLE
app won't sync

### ISSUE THREAD

**Issue by adnan-wahab** [MobileOrg/mobileorg#169]
tried with a blank .emacs config and same result

https://www.dropbox.com/s/4lpz8dx6hapm9sm/File%20Feb%2001%2C%208%2059%2011%20AM.png?dl=0

**Comment by mgmart** [comment]
Without knowing a bit more about your environment it's difficult to find an answer.

Did you follow the setup described in our [documentation](https://mobileorg.github.io) and Org mode's [documentation](http://orgmode.org/manual/MobileOrg.html#MobileOrg)?
Did you check wether the staging area is populated with files?
What iOS version are you on?
Do you use Dropbox or WebDav?

**Comment by adnan-wahab** [comment]
1. yes 
2. the staging area is blank
3. latest ios
4. dropbox

**Comment by webframp** [comment]
@adnan-wahab does org-mobile-push stage files in Dropbox for you?

**Comment by mgmart** [comment]
@adnan-wahab 
if 1. is yes, then there must be something in the staging-area :smile:
I think the solution should be easy. 

- determine where `org-mobile-push` creates your staging-files
- change that accordingly to your dropbox configuration
- try again

@MobileOrg/developers 
I've seen more occurrences of this issue on twitter and reddit.
From my point of view there are two action items:

- revise the documentation 
- give a clearer error message and 
  - probably advise to the user how to fix it.

**Comment by mgmart** [comment]
@adnan-wahab can you tell which version of org and emacs you are using?
Ideally you could post the complete output of `org-version` and `emacs-version`.

**Comment by mgmart** [comment]
Error messages are revised in #171

**Comment by mkasu** [comment]
I upgraded to the TestFlight beta from today and now I can't sync anymore. I'm not sure if it's related to this issue. My screen just says "Syncing orgmode files.. mobileorg.org" and hangs forever. I'm using WebDAV.

**Comment by mgmart** [comment]
@mkasu, thank you for reporting this.

We have rewritten the WebDAV code for this release. So this was most likely to happen. We need somehow to reproduce this. As our tests are all successful, we need to find out what triggers this behaviour.

With 1.7.1. (App Store release) everything still works fine?
Does the app recover if you kill it?

Could you provide some more information on your environment?

* iOS device, iOS version
* https connection  yes/no
* WebDAV server make and version (if possible)
  * Do you have access to the server logs?
  * Does the server need authentication?
* Any other information you think might be useful.

Feel free to open a new issue as this seems to be a different issue and we can track them differently, then.
