### ISSUE TITLE
[Build] Cocoa API Issue - stringWithString

### ISSUE THREAD

**Issue by vermiculus** [MobileOrg/mobileorg#17]
An insignificant portion of warnings generated from building the project as it is are of the form

> Cocoa API Issue
> Using 'stringWithString:' with a literal is redundant.

Is there a reason that this construct pops up throughout the source?  Is it in place to more easily support future localization/customization via actual `NSString`s, or is this some Objective C idiom I haven't come across before, or what?

I'd be happy to go through an make all the necessary changes if we reach a consensus on what to do.

**Comment by mgmart** [comment]
Warnings are gone. We haver others, though 🤓
