### ISSUE TITLE
Xcode compiled app crashes when switching to Dropbox if AppKey.plist isn't populated

### ISSUE THREAD

**Issue by abradd** [MobileOrg/mobileorg#173]
If the AppKey.plist isn't populated and the user switches to Dropbox in settings the app crashes and continuously crashes when attempting to start. Would be nice if this was handled more gracefully by warning the user or allowing them to select another option. Otherwise updating the documentation may help.

Xcode catches the crash if you compile while having Dropbox selected, but if you are compiling a fresh version of MobileOrg then the settings may not be populated and so the crash will not occur until you select Dropbox.

**Comment by mgmart** [comment]
Good point 😄
