### ISSUE TITLE
Core Data Concurrency Problem

### ISSUE THREAD

**Issue by mgmart** [MobileOrg/mobileorg#174]
At the bottom of #169 @mkasu reported a sync problem.

This is most likely a Core Data concurrency problem which occurred sometimes after the rewrite of the WebDAV code. The assumption is that the code now works way faster than before and that's too fast for Core Data 😄

**Comment by mkasu** [comment]
Thanks for opening the ticket. I'll put my reply here.

* With 1.7.1. (App Store release) everything still works fine?
* Does the app recover if you kill it?
* iOS device, iOS version

I'm using an iPhone 6S+ and iPad Air 2, both with iOS 10.2.1. The iPhone currently has TestFlight 1.7.2 and the iPad AppStore 1.7.1 so I can test it forth and back. The iPhone keeps hanging on every sync, the iPad works normally. 

I need to kill it (1.7.2) and then it works normally until I try to sync again. Interestingly, it even seems to sync some (all?) things despite hanging. When I trigger a sync on my iPad 1.7.1 client while the iPhone is hanging in sync, it already receives the changes made on my iPhone 1.7.2 (captured notes)

* WebDAV server make and version (if possible)

Seafile Pro 6.0.7. It seems to be "based on" WsgiDAV/1.2.0.pre according to the server headers.

* https connection yes/no
* Do you have access to the server logs?
* Does the server need authentication?

Yes, to all of them!

I'll play around with it more in the evening, so if I notice anything mention worthy I'll add it later.

**Comment by mgmart** [comment]
@mkasu it's most likely a Core Data problem. It's already addressed in #172 . So, no need to test further until the next TestFlight release. 

If you like you could try to build from my fork. But that only makes sense if you have some experience with xCode. Otherwise it will be more trouble than help for you.

**Comment by webframp** [comment]
I just want to say thanks @mkasu for the detailed report. It's the best detail we've received from a TestFlight user so far.
