### ISSUE TITLE
Is the use of a crash reporter worth the effort?

### ISSUE THREAD

**Issue by mgmart** [MobileOrg/mobileorg#175]
The last bugs reported by users were somehow hard to track down. We can't ask the user for their org files. Therefore to have access to crash reports might help. As it seems there were no crash reports provided within the Apple world (TestFlight, Xcode, ...). 

The use of an external service might help here. I stumbled across [Hockey App](https://hockeyapp.net) which is free for up to two Apps. There might be others.

**Comment by webframp** [comment]
I've head good things about Hockey App, but haven't used it myself.
