### ISSUE TITLE
Crashes if wrong encryption password is used during sync

### ISSUE THREAD

**Issue by laurynas-biveinis** [MobileOrg/mobileorg#177]
I have several large org files I'd like to sync with MobileOrg, using Dropbox.

In 1.7.1 from AppStore, a sync proceeds with several files, fills a progress bar for one of them, pauses, and quits the app.

In current git version running in a simulator, the same set of files results in sync stopped at an earlier file, and gives a "Bad file encoding", "Unable to detect file encoding, please re-save this file using UTF-8."

The error message did not say which file (or even if it was referring to the source .org file in the first place). I went through all my files with isutf8, and it pointed out several problems. I have fixed all of them and re-pushed, but 1.7.1 still crashes, and 1.7.2 still gives "Bad file encoding" error.

How do I proceed from here? Thanks

**Comment by mgmart** [comment]
That's bad. We should at least provide enough information in the error message.

Could you please check for `utf8` in your staging area? Maybe the `editsFile` is the cause of the problem.

If that's not the case we have to dig further a bit.

**Comment by laurynas-biveinis** [comment]
I might be confusing which dir I should look at - but the app directory in Dropbox does not have a file named editsFile, it only has checksums.dat in ASCII and the rest are encrypted binary files? Should I look somewhere else?

**Comment by mgmart** [comment]
Do you use file encryption?

**Comment by laurynas-biveinis** [comment]
Yes. Trying without...

**Comment by laurynas-biveinis** [comment]
OK! The results without encryption are: 1.7.1 crashes the same. 1.7.2 works

**Comment by mgmart** [comment]
The 1.7.1 crash could be caused by #174 although this has only happened with WebDAV so far. But maybe it's because of *large* files

**Comment by laurynas-biveinis** [comment]
The largest file in the 1.7.2 staging area, unencrypted, is 1.2MB

**Comment by mgmart** [comment]
That's big 😄 

Could you make sure that the password you are using is correctly entered in MobileOrg's settings? Somehow a wrong or not set password results also in `bad file encoding`

**Comment by laurynas-biveinis** [comment]
All previous 1.7.2 tests, including encrypted file ones, have been with no password entered (I forgot that I'm using encryption)

Not sure what was the password status of 1.7.1 before, likely it was present and correct. It still crashes with it re-entered.

1.7.2 with correct password works correctly too

**Comment by mgmart** [comment]
Good to know. Regarding 1.7.1 we [have some bugs fixed](https://github.com/MobileOrg/mobileorg/milestone/4?closed=1).

Sorry for the inconvenience. I'll investigate how we can signal that the password is missing.
