### ISSUE TITLE
`notesCount` not updating correctly (for the app-badge-icon)

### ISSUE THREAD

**Issue by vermiculus** [MobileOrg/mobileorg#18]
1. Create a new note, put whatever you want in it, and return to the notes view.
2. Delete the note.
3. The app badge does not decrement to reflect the deletion.

I've looked through the code for the `noteCount` updating (Classes/Capture/`NoteListController`/`-(void)refreshData`), but I can't make sense of the code inside `CountLocalNotes()` (in `DataUtils`)

**Comment by mgmart** [comment]
is it the app-badge or the badge on the tabbar-icon which is talked about?
The App does not show anything for me. The glitch with the capture-icon-badge is gone meanwhile.
Should be closed, shouldn't it?
