### ISSUE TITLE
Incorrect parsing if a heading level skipped

### ISSUE THREAD

**Issue by robertsck** [MobileOrg/mobileorg#182]
I ran across an issue today where a file is incorrectly parsed if a heading level is skipped. All file content is synced, however, on MobileOrg the heading levels are wrong. 

A simple example:

Org file: (Notice subheading 2.1 skips a heading level)

* Heading 1
** Sub-heading 1.1
** Sub-heading 1.2
* Heading 2
*** Sub-heading 2.1
* Heading 3
** Sub-heading 3.1

See the screen shots to see the effect after syncing to MobileOrg. Not sure if this is a MobileOrg issue, Org-Mobile issue, or the behavior is simply un-defined at this time. 

![img_0334 png](https://cloud.githubusercontent.com/assets/5769073/23481688/58584128-fe9a-11e6-9c45-f3d2f1b86563.png)

![img_0335 png](https://cloud.githubusercontent.com/assets/5769073/23481694/5adb8a54-fe9a-11e6-8721-e6daf5466e4d.png)

**Comment by jonathanwilner** [comment]
Is this possibly the same as #163?

**Comment by robertsck** [comment]
I don't think so. The app is not closing or crashing. Everything is synced,
it's just that the heading levels do not match from computer to MobileOrg.

I'm testing the Master build on my device. I can try the Develop branch and
Xcode emulator to see if those permutations make any difference.

**Comment by mgmart** [comment]
@robertsck did you have success with `develop`?

**Comment by robertsck** [comment]
Just tested this on Develop and it does appear to be working correctly.
I’ll stick with Develop going forward to prevent confusion.

Chris

On March 6, 2017 at 11:28:06 AM, Mario Martelli (notifications@github.com)
wrote:

@robertsck <https://github.com/robertsck> did you have success with develop?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MobileOrg/mobileorg/issues/182#issuecomment-284449618>,
or mute the thread
