### ISSUE TITLE
Version 1.7.2 of Encrypted features are buggy

### ISSUE THREAD

**Issue by frapples** [MobileOrg/mobileorg#189]
Some info:
```
Iphone: iphone SE
IOS version: 10.2.1(14D27)
Emacs version: 25.1.1 (Debian stretch)
Org-mode version: 9.0.5, 
```

My configuration in the previous version 1.7.1 is no problem, it works fine.

One day I updated MobileOrg, when I sync on the phone, the display of the error message:
```
Unable to detect file encoding, please re-save this file using UTF-8.
```
I tried to delete the files inside my webDav, 
and then put my org file inside only into English (my mother tongue is not ASCII characters), again synchronized.
But the problem remains the same.So the reasion isn't encoding.

I tried to emacs and MobileOrg config about password switch off,
then delete files inside webDav, and then sync.
This time works fine.

I tried a very simple password, so password could not be typed wrong.
By looking at the value of the variable org-mobile-encryption-password, the emacs password configuration is correct.

Also, in the mobileorg settings page, enter the password inside the column which will display some black points.
But when i close mobileorg and then start, the password inside the column becomes empty.
However, this situation password should be valid,
because I sync after looking at webdav inside the mobileorg.org file found to be encrypted.

I do not know if this is not the expected behavior.

**Comment by mgmart** [comment]
I could only reproduce the issue with the password field not being initialised in settings-view.

Maybe this has caused the hassle. Once #190 is merged we will see further on this issue.
