### ISSUE TITLE
Item editing should be cancellable

### ISSUE THREAD

**Issue by mgmart** [MobileOrg/mobileorg#193]
Once text is edited, done button should be enabled.

Also it would be expected that the back button would trigger a cancel operation.

<img width="187" alt="glass" src="https://cloud.githubusercontent.com/assets/3919652/26032893/259add9c-389f-11e7-8f14-0f3c35795e88.png">

**Comment by DivineDominion** [comment]
See #216, I think the back button should not cancel at all because note editors are neither forms (like creating an event in Calendar) nor settings.

**Comment by dive** [comment]
Closed due to changes within #251.
