### ISSUE TITLE
suggestion for todo states with swipe

### ISSUE THREAD

**Issue by pvinis** [MobileOrg/mobileorg#195]
hello.
i thought it would be cool to do this:
lets say we have a list item, that is `TODO`. then i can swipe to the right, and it will go to `NEXT`. then i can swipe again and it will go to `DONE`. swiping left will put it back to `NEXT`.

does that sound interesting? it would be even better if it can get the "next" state the same way org-mode gets the next state, either by the top file todo tags, or custom ways.

**Comment by mgmart** [comment]
@pvinis,

sorry for late reply. 

Could you please issue this idea in the project we've set up for the [next release of MobileOrg](https://github.com/MobileOrg/mobileorg.next)? The project is still active even if there was less to none participation in the last couple of month. I'm pretty sure that we would get up to light speed as soon as there are couple of collaborators willing to participate 🙂.

**Comment by mgmart** [comment]
was added to 2.0 project
