### ISSUE TITLE
Failure: -1001 while fetching checksum.dat from Nexcloud

### ISSUE THREAD

**Issue by mika-fi** [MobileOrg/mobileorg#198]
I use org-mobile version 1.7.2 on IOS using my own Nextcloud instance as a webdav server (it runs on ubuntu)

In Nextcloud I created a folder called Notes which contains index.org, checksum.dat (generated using md5sum) and Notes.org (which is referred to by a link in index.org)
I set all the parameters for org-mobile in emacs to enable org-mobile-push, which worked perfectly.

In the app, my webdav configuration is https://[my.server]/nextcloud/remote.php/webdav/Notes/index.org
When I hit the sync button it fails after few seconds. The error message is : 
"Error downloading checksums
This file isn't required, but the error received was unusual
Failure: -1001"

I don't know how to provide more information, please guide me if you need more details.

**Comment by mgmart** [comment]
@mika-fi could you please recheck with the now available v1.7.3?

**Comment by webframp** [comment]
@mika-fi this issue should be resolved in the latest version which includes numerous webdav fixes. Can you test with v1.74 and report back? Thanks

**Comment by mickaelfiorentino** [comment]
Hi @webframp, thanks for the fixes it now connects correctly.
