### ISSUE TITLE
Font size should be adjustable

### ISSUE THREAD

**Issue by Logicxcz** [MobileOrg/mobileorg#204]
I found i can change the text size on my iphone, but the layout did not adjust ,will the function be added? 

Or, may i set the text size in settings?

**Comment by Logicxcz** [comment]
May be i didn't describe clearly . When i view as documents the text size is too small. I want it to be bigger.

**Comment by mgmart** [comment]
This might help with implementing the enhancement: https://useyourloaf.com/blog/auto-adjusting-fonts-for-dynamic-type/

**Comment by Logicxcz** [comment]
Thanks very much !
