### ISSUE TITLE
MobileOrg crashes and stays crashed

### ISSUE THREAD

**Issue by clfest** [MobileOrg/mobileorg#207]
I have updated to 1.7.4, but alas MobileOrg still crshes, and stays crashed, necessitating a reinstall
of MobileOrg, and losing any data that was on my iPhone that hadn't been synced. This is a continuation
of closed issue #196.

**Comment by clfest** [comment]
Again crashed same symptoms (8/31/17 approx 2:00 AM). Have to reinstall, I guess.

**Comment by myrjola** [comment]
I have the same problem. The last thing I was doing was editing a note. The next time I open the app it crashes and won't recover without deleting the data. I am sharing crash data with developers, so hopefully the crash dumps have arrived to you.

**Comment by clfest** [comment]
I'd be glad to share my crash data with the developers, how do you do this?

**Comment by myrjola** [comment]
> I'd be glad to share my crash data with the developers, how do you do this?

https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AnalyzingCrashReports/AnalyzingCrashReports.html#//apple_ref/doc/uid/TP40012582-CH21-SW2

**Comment by mgmart** [comment]
Any news on this?

**Comment by clfest** [comment]
I seem to have done the above steps. By the way my MobileOrg on my iPhone
became inoperative in the same way were talking about on 10/19/17.

**Comment by mgmart** [comment]
@clfest could you please give us an update on the versions you are using?

**Comment by mgmart** [comment]
@webframp any chance to get to the crash logs?

**Comment by clfest** [comment]
I am using 1.7.4.

**Comment by mgmart** [comment]
@clfest, there might be something in the files in your staging area which is causing the issue you are reporting. 

- Do you still have the problem if you wipe the staging area and do a fresh push?
- Does the problem persist if you create some testfiles and push those into a cleaned  staging area?

**Comment by mgmart** [comment]
Ticket is stale for more than 3 month
