### ISSUE TITLE
unsupported encoding of the text

### ISSUE THREAD

**Issue by mpslxz** [MobileOrg/mobileorg#208]
Captures from the device are encoded in an unsupported format that when pulled into org mode, emacs cannot recognize the encoding.

**Comment by mgmart** [comment]
Do you use an other encoding than UTF-8 on your Emacs?

@mpslxz, could you please provide us with the versions you are using?

iOS version. Org Mode version. MobileOrg version. Emacs version.

**Comment by mpslxz** [comment]
@mgmart My encoding is UTF-8. 
iOS version 10.3.3 
org mode: 9.0.10
mobileorg: 1.7.4
emacs: 25

**Comment by mgmart** [comment]
@mpslxz, could you check if the files in your staging area are still UTF-8?
Do you use WebDAV or Dropbox?
It might help if you could provide the files residing in your staging area to us. Probably best by pushing some test-files without any personal data there first.

**Comment by mgmart** [comment]
Issue is stale for more than 3 month.
