### ISSUE TITLE
FR: add MobileOrg to the ios 'Share' menu

### ISSUE THREAD

**Issue by yatesco** [MobileOrg/mobileorg#209]
Hi - newbie here.

Can MobileOrg be added to the iOS's 'share' menu? For example, in Safari when I click 'share'  choosing MobileOrg' would then add that link as a 'captured' note?

I searched around and couldn't find any prior discussion on this, which surprised me as I thought this was a pretty fundamental need, so maybe I have missed something :=).

Thanks!

**Comment by mgmart** [comment]
Thank you for your input. We've already got this on our [feature list](https://github.com/MobileOrg/mobileorg.next/blob/specification/docs/MobileOrgv2.org#features).

We'd be happy if we would get additional input on this.
