### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by dathinaios** [MobileOrg/mobileorg#211]
Hello,

First of all thanks for working on this! I was looking for a way to access my org files on iOS 👍 

One thing that I find an obstacle in using the application is the UI design. Now I know this is a matter of taste but here are some initial personal observations:

* The nested table does not reflect the way we are used to work with org mode and is in general braking the visual convention of an outliner. I would propose using collapsible menus (maybe like the ones described [here](https://medium.com/ios-os-x-development/ios-how-to-build-a-table-view-with-collapsible-sections-96badf3387d0)?).
* The small circular info button is distracting and should not be constantly visible. Tags, priority, todo states etc, would be better accessed only through a swipe gesture. A gentle circular indication could provide a glimpse of states.

Thanks!

**Comment by mgmart** [comment]
Thanks for your input. We've collecting requirements, ideas proposals to a new version of MobileOrg here: [MobileOrg.next](https://github.com/MobileOrg/mobileorg.next/blob/specification/docs/MobileOrgv2.org#features). 

We would appreciate if we'd get some more input on this.
