### ISSUE TITLE
Feature Request: SSH Sync

### ISSUE THREAD

**Issue by systole** [MobileOrg/mobileorg#23]
One of the features I am hoping to work on once the initial app is released is the ability to sync via SSH in addition to Dropbox and WebDav.

**Comment by mgmart** [comment]
Needs some clarification: rsync over ssh? in v2 git over ssh could be an approach if we are going that way.

**Comment by 501st-alpha1** [comment]
I keep my Org Mode files in a Git repo, so I'm in favor of that if it's an option.

**Comment by mgmart** [comment]
@501st-alpha1 I made that a question(#120)

**Comment by mgmart** [comment]
covered by requirements
