### ISSUE TITLE
Dropbox folders not showing

### ISSUE THREAD

**Issue by WouterSpekkink** [MobileOrg/mobileorg#232]
Hi there,

First of all, thanks for writing this software.

Unfortunately, I am having trouble getting it to work. I can download the app for Android (my Fairphone 2 runs Android 6.0.1), and I can then go through the setup wizard. I successfully logged in to my Dropbox account, but then, in the next screen, no folders are shown. The issue might be similar to issue #73, but also if I create the folder on Dropbox manually, nothing shows up in the MobileOrg app (I can successfully push files to the manually created Dropbox folder from emacs).

Any idea what might be causing this? Thank you in advance.

**Comment by michaeleverson** [comment]
This is the iPhone app, unfortunately, which is separate. I'm not sure where you should report your bug.

**Comment by gvol** [comment]
Presumably at https://github.com/matburt/mobileorg-android

**Comment by WouterSpekkink** [comment]
Hi both, thanks for answering, and my apologies for not paying enough attention to notice that I was posting this issue at the wrong repository. I'll close it now. Thanks again.
