### ISSUE TITLE
Capture: Option to add newline before timestamp

### ISSUE THREAD

**Issue by novoid** [MobileOrg/mobileorg#236]
MobileOrg v0.9.13 on OxygenOS 9.0.0 (Android 9)

When I do capture an article, e.g., using NewsBlur RSS app, this results in an entry like this:

```
* NEXT This is the title of the article
https://this.is.the.url/of/the/article.html[2019-01-22 Tue 22:17]
```

Notice the time-stamp who is directly appended to the URL without even a space character in-between?
This is at least annoying to me.

Could you please offer any help with that? Option to add a newline before the timestamp? Adding a newline between any content and the timestamp in any case? ...

Thank you very much!

**Comment by webframp** [comment]
Hey @novoid ! Sorry this repo is for the iOS app not the android one.

**Comment by novoid** [comment]
Wow, I didn't know that there _is_ a MobileOrg for iOS.

Sorry!
