### ISSUE TITLE
MobileOrg folder not created when linked with Dropbox

### ISSUE THREAD

**Issue by sati-bodhi** [MobileOrg/mobileorg#239]
After linking with Dropbox, the MobileOrg folder is not created. Even when  the said folder is created manually with agenda files successfully staged, the app fails to read and access the files in it. Syncing does not result in an error, but outlines and all remain empty. 

ios version: 11.2.1 (15C153)

**Comment by bshanks** [comment]
I have this problem too.

**Comment by minostro** [comment]
I didn't experience that issue.

MobileOrg version: 1.7.4
ios version: 12.4

**Comment by webframp** [comment]
I haven’t been able to recreate this issue with the current develop branch. Please reopen if still a problem.
