### ISSUE TITLE
Trying to sync Spacemacs with mobileorg

### ISSUE THREAD

**Issue by kimfucious** [MobileOrg/mobileorg#240]
Hi there,

I love this idea, but alas, I can't seem to get past the starting gate.

- I've got the app running on mobile.
- There is a ~/Dropbox/Apps/MobileOrg now created

In the docs found, [here](https://mobileorg.github.io/documentation/#using-dropbox), it says:

```console 
You should edit your Org mode configuration to contain something like this:
;; Set to the location of your Org files on your local system
(setq org-directory "~/org")
;; Set to the name of the file where new notes will be stored
(setq org-mobile-inbox-for-pull "~/org/flagged.org")
;; Set to <your Dropbox root directory>/MobileOrg.
(setq org-mobile-directory "~/Dropbox/Apps/MobileOrg")
```

I'm assuming this goes in the .spacemacs dot file under `user-config`, correct?

It also says:

```console
You can run org-mobile-push by pressing C-c C-x RET p whilst you are in an Org buffer.
If you use spacemacs just type: SPC q r
```
Neither of those keystroke sequences work for me, nor can I find the `org-mobile-push` command anywhere.

I'm running Emacs 26.3 and the development branch of Spacemacs v. 0.300.

Any help/advice is much appreciated.

**Comment by webframp** [comment]
Hi Kim, thanks for reporting this. I’ll try to recreate your scenario and see what I can recommend. I have some spacemacs experience so I’ll let you know.

**Comment by kimfucious** [comment]
Hey @webframp ...

I think I figured out my issue.  I needed to have an org file open in order for `org-mobile-push` to be visible in the menus.  My bad 😊

**Comment by webframp** [comment]
@kimfucious that would do it 😁 

Thanks for checking out MobileOrg, let me know via issues here how it can be improved. I'm slow to make changes but open to ideas.
