### ISSUE TITLE
Investigate switch from CocoaPods to Carthage.

### ISSUE THREAD

**Issue by webframp** [MobileOrg/mobileorg#247]
Determine if switching to Carthage and removing the dependency on CocoaPods to allow using `xcconfig` files is worth the effort (probably, yes).

* https://github.com/Carthage/Carthage

This should also enable removing the multiple plist config with various build settings (adhoc,debug,release). 

Using the latest BuildSettingExtractor release could help with migration:
* https://github.com/dempseyatgithub/BuildSettingExtractor/releases/tag/v1.3.2

**Comment by jdek** [comment]
I started working on this, I have a WIP in my fork. Though I will only be able to finish it in January when I get my mac back from repair.

**Comment by webframp** [comment]
Thanks @jdek feel free to open a draft PR anytime you want input!
