### ISSUE TITLE
Drop support for anything below iOS 12

### ISSUE THREAD

**Issue by webframp** [MobileOrg/mobileorg#250]
Looking for user input on this one. Dropping support for older platforms does enable us to begin using the latest features available in iOS dev.

Based on App Store metrics this is our user version distribution over the last 30 days:
![image](https://user-images.githubusercontent.com/774378/67118968-1299fe00-f1b4-11e9-9d51-b5e6b48672bd.png)

If we were to drop support for versions 9, 10 and 11 of iOS we would alienate 3 current users it seems. 

I'm curious to know how users feel about this kind of change.

**Comment by webframp** [comment]
@dive we can try to collect info here on versions to support. If we don’t get any feedback, we can drop the old iOS versions

**Comment by webframp** [comment]
Haven’t had much feedback after 1 month. @dive I think we would be safe to drop the older platforms of you are still interested in contributing

**Comment by dive** [comment]
@webframp, yeah, I can do it. But I think it is reasonable to wait for #247.

**Comment by webframp** [comment]
> @webframp, yeah, I can do it. But I think it is reasonable to wait for #247.

I agree, probably best
