### ISSUE TITLE
Android version?

### ISSUE THREAD

**Issue by muellert** [MobileOrg/mobileorg#254]
I just came across this project and wondered whether there might be an Android version. The original version on Android is really old and lacking in many ways. Looking at the source code, it should not be easy, though. Any suggestions?

**Comment by webframp** [comment]
Hey @muellert you’re right, this code is very iOS specific. 

The only android repo I knew of was:
https://github.com/matburt/mobileorg-android

But it seems like @matburt is no longer maintaining it or using org. 

This may be an active fork:

https://github.com/hdweiss/mobileorg-android

Hope you find something!

**Comment by matburt** [comment]
currently no one is maintaining any active mobileorg for android fork that I know of. There *are* some alternatives out there you just have to search for them.

**Comment by muellert** [comment]
On Tue, Dec 03, 2019 at 08:05:15AM -0800, Matthew Jones wrote:
> currently no one is maintaining any active mobileorg for android fork
> that I know of.

That describes exactly my current impression.

> There *are* some alternatives out there you just have
> to search for them.

Interesting. I searched the Play store and also Fdroid, but could not
find anything so far. A full emacs port doesn't count from my POV,
because it's really too heavy for a handset (I don't use tablets). The
wiki in the original project has also been disabled completely, so I
currently just have the two code bases sitting on my disk, waiting for
me to spend inordinate amounts of time, getting into it.

As a general note, having the same app on both iOS and Android, and in
sync, would be a nice thing.
