### ISSUE TITLE
Move license to GPLv3

### ISSUE THREAD

**Issue by webframp** [MobileOrg/mobileorg#26]
Opening an issue to allow for discussion. Org-mode uses GPLv3, http://orgmode.org/cgit.cgi/org-mode.git/tree/COPYING

Could we also? For a description of why: https://www.gnu.org/licenses/rms-why-gplv3.html

Despite the basic incompatibilities of the App Store and the GPL, the legal issues are Apple's and under the current license the same risk of getting pulled from the store at Apple's discretion exists.

**Comment by mgmart** [comment]
No traffic for nearly 4 years. Please reopen if question should still be discussed.
