### ISSUE TITLE
Why generates new mobileorg.org files?

### ISSUE THREAD

**Issue by coldfish** [MobileOrg/mobileorg#275]
I really don't understand why app generates a new mobileorg-(number).org file again and again after each capture. Am I missing something? Can it be related with corruption in iCloud sync system?

I'd be glad if you have any suggestions.

**Comment by coldfish** [comment]
I think there's a sync problem. After removed the mobileorg.org file, it started to create/update the main file.

**Comment by dive** [comment]
Hi @coldfish. This is definitely a bug within the iCloud implementation logic as described [here](https://github.com/MobileOrg/mobileorg/issues/271#issuecomment-695212134) (#271). Unfortunately, I am plodding on the fix due to lack of free time.

**Comment by coldfish** [comment]
@dive thanks for the explanation. After manually downloaded the items, it seems working.
