### ISSUE TITLE
Search does not show any notes

### ISSUE THREAD

**Issue by JCZuurmond** [MobileOrg/mobileorg#283]
The notes are visible in outlines, but the search tab does not show any of them. I use mobile org`version: 1.7.5` on iphone with Ios version `15.0`

**Comment by webframp** [comment]
Hey @JCZuurmond sorry you're having issues. I use the search myself and haven't noticed a problem but could you describe a specific scenario I can recreate?

I'll see what I can find out. Thanks!

**Comment by JCZuurmond** [comment]
Hi @webframp, my specific situation is quite general: I was able to load my notes from a nextcloud server using the webdav protocol - I see them under "outlines" - but nothing shows in the "search" tab.

What info can I provide to help you understand the problem better?

**Comment by JCZuurmond** [comment]
I made a mistake somewhere, it just works fine! Thanks for your response @webframp
