### ISSUE TITLE
Agenda stuck in week 40

### ISSUE THREAD

**Issue by parasit** [MobileOrg/mobileorg#288]
Hi,
Couple weeks ago I found and install MobileOrg on my phone. Everything works well, except continuous Dropbox token expiration, but I can live with this. 
However, after some time it turned out that in the view of the agenda (any) I still have “Week 40” (now is 43) and I can’t change it in any way. Am I doing something wrong or is it some kind of bug in application?

![D97E9EDC-C170-485A-AE1E-11682BFA1A78](https://user-images.githubusercontent.com/310182/197755649-52018184-6a59-4b31-8f12-80d8a03285ff.jpeg)

**Comment by mgmart** [comment]
The agenda is generated on the emacs side by issuing `org-mobile-push`.

**Comment by parasit** [comment]
Thanks for the answer, maybe it would be nice to add this information to the FAQ? :)
