### ISSUE TITLE
Syncing loses time information

### ISSUE THREAD

**Issue by 0-wiz-0** [MobileOrg/mobileorg#31]
When I "Capture" a note in mobileorg and then sync it, the entry time is weirdly modified. Usually to 1999.
Attached are two example screenshots, directly before and after a webdav-sync (I think I left the sync screen and went back to it). As you can see, the date of the upper entry was changed from 2013-04-23 to 1999-12-28, but the time stayed the same.
![before](https://f.cloud.github.com/assets/2221844/416082/0418a55e-ac45-11e2-9580-5cb76afb4223.png)

![after](https://f.cloud.github.com/assets/2221844/416099/8620303a-ac45-11e2-98c9-01cf296aa3a5.png)

**Comment by mgmart** [comment]
Does't occur anymore.
