### ISSUE TITLE
Can we get iOS5 support back?

### ISSUE THREAD

**Issue by bmonreal** [MobileOrg/mobileorg#43]
MobileOrg is no longer usable on 1st-generation iPads, which cannot install iOS 6.   

I find it hard to understand why it's not compatible with an the older OS.  It doesn't need to interact with Siri, or front-facing cameras, etc.., (at least not as its main job, which is displaying text and lists and agendas.)   I would like to request that iOS5 support be brought back if at all possible.

**Comment by mgmart** [comment]
Due to the use of DropboxAPI v2, Swift & Cocoapods the support if iOS 5.0 is probably not possible anymore.
