### ISSUE TITLE
Dropbox folder is different with different iOS locale

### ISSUE THREAD

**Issue by zmx** [MobileOrg/mobileorg#50]
My iPhone language is Chinese, I need change .emacs settings to make sync works.

Not Works:
(setq org-mobile-directory "~/Dropbox/Apps/MobileOrg")

Works:
(setq org-mobile-directory "~/Dropbox/應用程式/MobileOrg")

Maybe MobileOrg should provide a page show the correct path for user.

**Comment by mgmart** [comment]
Would like to close this because we can not determine the locale used by emacs from iOS.
