### ISSUE TITLE
Agenda view showing date but not time (IGNORE, wrong post)

### ISSUE THREAD

**Issue by Nikolai1** [MobileOrg/mobileorg#54]
IGNORE:
My agenda view on my phone presents my scheduled APPOINTMENTS  with correct dates, but the timepoint is missing.

Are the Dropbox/MobileOrg/agendas.org  timepoints corrupted?:
- Week-agenda (W43-W44):<after>KEYS=a TITLE: Agenda </after>
  *\* Wednesday     23 october 2013
  **\*  MEETING Boss <before>Meeting:       11:00-12:00</before>
  
  :PROPERTIES:
  :ORIGINAL_ID: 898e39cd-1e35-467f-b30b-5d2c73b3dea9
  :END:

**Comment by mgmart** [comment]
ignored 😄
