### ISSUE TITLE
Editor window size on iPhone 5

### ISSUE THREAD

**Issue by cigumo** [MobileOrg/mobileorg#57]
The editor window height appears smaller on the iPhone 5, both in the capture new note and in the edit body window. It seems the height is fixed to the previous screen sizes when the keyboard is shown.  On the iPad it works OK. 

I'm not sure if it's related but it's also difficult to scroll in these windows to see the bottom of the text when it goes outside the screen.

The following images show how the text is cut and there is a white band between it and the keyboard. 

![image](https://f.cloud.github.com/assets/934821/1913163/052340ae-7d45-11e3-90f8-7fca9aaaf5b2.png)
![image-1](https://f.cloud.github.com/assets/934821/1913164/0548bf6e-7d45-11e3-94fc-19c1909f90e1.png)

Oh, and thanks _a lot_ for keeping MobileOrg alive!

**Comment by webframp** [comment]
I've been slowly working on this as my time allows and plan to get a new release in the next 30 days or so.

**Comment by mgmart** [comment]
This is probably related to #46

**Comment by mgmart** [comment]
Should be fixed by #112
