### ISSUE TITLE
Mobile Org support for non emacs users

### ISSUE THREAD

**Issue by athanassis** [MobileOrg/mobileorg#58]
Hi, 
Would it be possible to support that?
I would like to upload my org files to drop-box via other ways, e.g., via a script via the dropbox api, not emacs-orgmode built-in pull method.
But I cannot make MobileOrg to download them to iPhone. I get the same error presented in the screenshots in https://github.com/MobileOrg/mobileorg/issues/32

Is it a matter of some indexing I don't provide? What should be the format of the index.org file and where should it be put in the dropbox folder?

Thanks!

**Comment by shaiguitar** [comment]
@athanassis you might find spacemacs ( https://github.com/syl20bnr/spacemacs ) a try. It's a great "up and running" entry to emacs coming from vim. I use it and like it a lot.

**Comment by trejkaz** [comment]
Another vote for this. I was looking at using the orgmode addon for Sublime Text.

The main issue seems to be requiring checksums.dat but updating that manually every time I make an edit would suck.

Dropbox already has ways to figure out whether a file has changed: https://www.dropbox.com/developers/core/docs#metadata

**Comment by vermiculus** [comment]
Keep in mind that MobileOrg doesn't depend on Dropbox. It will work with WebDAV/etc. as well.

**Comment by trejkaz** [comment]
Keep in mind that not depending on something doesn't mean that you can't take advantage of its features.

**Comment by vermiculus** [comment]
Why can't you (or the orgmode plugin for st) automate checksums.dat? Put a hook on sublime's save function to recalculate the checksums if it's saving a tracked file. You could feasibly even add such a hook to dropbox itself.

**Comment by trejkaz** [comment]
Better question: why do we even need checksums.dat when there is already a way to get the current checksum of a file?

**Comment by vermiculus** [comment]
Because we need to track which files changed so we know which to download. ([Reference](http://mobileorg.ncogni.to/doc/getting-started/syncing-with-mobileorg))

**Comment by trejkaz** [comment]
I'm pretty sure that even WebDAV has ETag which could be used to do that, though, and Dropbox of course has the method I already linked the docs to.

Any other reasons?

**Comment by vermiculus** [comment]
Nope, that's pretty much it. :smile:

Except for the fact that checksums.dat is part of Org's implementation which doesn't even rely on the internet. Hidden data like this is exactly what the Org format tries to avoid.

**Comment by athanassis** [comment]
On my laptop:
I have created index.org and checksums.dat files per instructions by @joelmccracken (md5 used)
Then uploaded both files plus my org files to dropox inside home/Apps/MobileOrg.

On the MobileOrg App side now:
after linking my dropbox account and when pressing synch button I get following error:
"Error synching changes, an error was encountered while attempting to fetch **mobileorg.org** from the server. The error was: Unexpected error"

So do I need another mobileorg.org file? 
What should be the contents? 
Should it included in index.org and checksums.dat?

**Comment by mrkeuz** [comment]
I found simple workaround.
Inside _~/Dropbox/Apps/MobileOrg_ just create _index.org_ with any content. 
And next execute:
`$ md5sum index.org > checksums.dat`  
I thing it should help.

**Comment by athanassis** [comment]
Thanks mrkeuz and all!
I finally got to make it work. An empty mobileorg.org file was enough to get the app working.

**Comment by webframp** [comment]
@mrkeuz thanks for posting the solution you found, hopefully helpful to other users. Honestly glad to see this code is still useful to some people besides just me.

Should probably add this to a troubleshooting section for the website: http://mobileorg.github.io/

**Comment by mgmart** [comment]
Closing this to get the issues section clean.
Created a task in MobileOrg/mobileorg.github.io for further reference.
Could be reopened anytime, though.
