### ISSUE TITLE
Support for BitTorrent Sync

### ISSUE THREAD

**Issue by zbeekman** [MobileOrg/mobileorg#60]
Cloud services like Drop Box are not ideal because you are entrusting your data to a third party. [BitTorrent Sync](http://www.getsync.com) synchronizes data between multiple devices using an encrypted p2p protocol, cutting out the middle man. Sync clients are available for iOS, Android, and desktop computer clients (apple, Microsoft, Linux)

**Comment by zbeekman** [comment]
There's also SyncThing: https://github.com/syncthing/syncthing ... Does anyone know if additional sync options have been added beyond dropbox?

**Comment by mgmart** [comment]
Requirements does not explicitly mention BitTorrentSync at the moment. But topic is covered by pluggable sync modules.
