### ISSUE TITLE
BUG: Heading level skips

### ISSUE THREAD

**Issue by nicholascarroll** [MobileOrg/mobileorg#62]
In Outline view, when an org file has a level 1 heading and then a level 4 heading directly under it, it will show these, but will then lose the rest of the document. eg.

\* Heading 1
***\* Heading 1.1.1.1
*\* Heading 1.2
* Heading 2

In the example above, the top level view in Outline will show:
Heading 1
Heading 1.2
whereas it should show
Heading 1
Heading 2

**Comment by mgmart** [comment]
Could reproduce the cutting-off of the rest of the document one time only. Stripping of Heading 1.1.1.1. still reproducable.
