### ISSUE TITLE
ER: Image support

### ISSUE THREAD

**Issue by nicholascarroll** [MobileOrg/mobileorg#63]
Please enable Mobileorg to display image links in the Document View. For example you would insert this line into node.m

```
// image link
{
    NSString *regexString = @"\\[\\[file:([a-zA-Z0-9/\\-\\._]+\\.(?:jpg|png))\\]\\[([a-zA-Z0-9/\\-_\\. '!?]+)\\]\\]";
    line = [line stringByReplacingOccurrencesOfRegex:regexString withString:@"<a href='file:$1'>$2</a>"];
```

and whatever required changes to allow the link to be tapped by the user and display the image, without having to leave the app.

**Comment by mgmart** [comment]
For that mobile-org has to export the linked images. Is that possible? If not we should close this issue.

**Comment by webframp** [comment]
As far as I can tell syncing of referenced images is unsupported by `M-x org-mobile-push` at this time. The list of files is determined by the `org-mobile-files-alist` function: http://orgmode.org/cgit.cgi/org-mode.git/tree/lisp/org-mobile.el#n257

It uses the value of `org-mobile-files` http://orgmode.org/cgit.cgi/org-mode.git/tree/lisp/org-mobile.el#n47 which is designed to just look for files ending in `*.org` right now.

This means image display could only work for remote images that could be downloaded. I'm open to the idea of image display, but I don't think it will be a priority for some time.
