### ISSUE TITLE
No option to reuse MobileOrg directory with installation of MobileOrg on multiple devices

### ISSUE THREAD

**Issue by mannd** [MobileOrg/mobileorg#66]
In order to use MobileOrg on multiple devices I have had to temporarily rename the preexisting MobileOrg staging directory in Dropbox, and then delete the created MobileOrg directory and rename the original directory back to MobileOrg.  If I don't do this, the installation will see the MobileOrg directory and create a MobileOrg(1) directory instead.  There should be an option to use a preexisting MobileOrg directory.

**Comment by mgmart** [comment]
Can't reproduce that. Probably gone meanwhile. Probably due to the use of Dropbox API v2.

**Comment by webframp** [comment]
Assuming APIv2 fixes this as well, since I haven't seen this behavior. Can re-open the issue if it persists.
