### ISSUE TITLE
org-mobile-push attempts to interpret in-buffer export settings

### ISSUE THREAD

**Issue by redtoade** [MobileOrg/mobileorg#69]
Throws this error:

"error("Before first headline at position %d in buffer %s" 104 #<buffer requirements.org>)"...
org-back-to-heading(t)

when my org file has a timestamp before the first heading, for example:
# +DATE:        <2015-03-17 Tue>

**Comment by mgmart** [comment]
Can't reproduce that. Probably gone meanwhile?

**Comment by webframp** [comment]
Agreed, same result for me
