### ISSUE TITLE
url at top of github project page should point to new website

### ISSUE THREAD

**Issue by zbeekman** [MobileOrg/mobileorg#71]
rather than just having a circular link back to the github page

**Comment by vermiculus** [comment]
…and which website would you suggest? (there are at least two reasonable options)

**Comment by zbeekman** [comment]
hmmm, well reading further down the README, it seems like the official webpage is http://mobileorg.ncogni.to, or at least it seems this way to me, someone who has no official connection with the project. If there is another place I should be looking, instead or in addition, then I would also love to know about it. Basically, I just don’t think it’s clear where to go to get more info about documentation etc. from the README

**Comment by webframp** [comment]
This could definitely be clarified in the readme. 

A revamped site was started here, but hasn't been completed, the plan was to update things once the new site was ready. Any documentation writers interested?

Site: http://mobileorg.github.io

Code: https://github.com/MobileOrg/mobileorg.github.io/

**Comment by zbeekman** [comment]
@webframp Yes, this is the URL at the top of the project page, but in its current state the webpage is confusing and unhelpful. For example, the news section:

> MobileOrg has a new website!

Where? Here?

> Learn More

This just takes you back to the github project page and README. But at the top of the project page there’s a link to http://mobileorg.github.io/

In short, currently the new website (http://mobileorg.github.io/) contains nothing useful at the moment and shouldn’t be the main URL of the project until it does. Further, the links at the top of the project page point you to the website, which then just points you back to the project page for more details. Until you have something useful at http://mobileorg.github.io/ the project page (at the top) should still point to http://mobileorg.ncogni.to/ IMO

**Comment by zbeekman** [comment]
New site is still useless to users...
