### ISSUE TITLE
DropBoxKeys

### ISSUE THREAD

**Issue by shaiguitar** [MobileOrg/mobileorg#75]
Using the app and it works great.

I want to help contribute to this project but I can't seem to get it to run in xcode due to needing some certificate:

http://shairosenfeld.com/uploads/mobile-contrib.png

https://gist.githubusercontent.com/shaiguitar/8485b70e81880ef751d0/raw/a60c78175f81a8e9d4046c41a540b41f43b61b3b/gistfile1.txt

Is there some kind of FAQ on how to set up local dev or get the APP_KEY/APP_SECRET keys and/or whatever else is necessary?

**Comment by webframp** [comment]
Hey @shaiguitar glad you're willing to help out, we could use it!

It seems like there are actually two key related issues here. The first is related to the iOS dev process, from the image it looks like you need a code signing certificate. For local development at least you should be able to create your own and use that, temporarily.

For the DropboxKeys, there is a file in the repo named `DropBoxKeys.xcconfig.dist` that has further information.

It should look like this:
```
//
//  DropBoxKeys.xcconfig
//  MobileOrg
//
//  Copy this file to DropBoxKeys.xcconfig and add the correct keys. 
//  Do not use quotation marks or constrant string notation (@)
//
//
//  DropBoxKeys.xcconfig
//  MobileOrg
//
//  Copy this file to DropBoxKeys.xcconfig and add the correct keys. 
//  Do not use quotation marks or constrant string notation (@)
//

APP_KEY = <put key here>;
APP_SECRET = <put secret here>; 
```
For dev purposes these can also be just private ones that you generate for yourself. You can do this by creating an 'app' in the dropbox developer site here: https://www.dropbox.com/developers/apps

then substituting the right values.

Hope that's enough to get you going, some of the other contributors can chime in with additional tips as needed I'm sure.

**Comment by webframp** [comment]
This process has changed slightly.

@shaiguitar Check out the recent changes for Xcode 8 that have been merged into develop branch. You'll need to edit this file to add your testing keys: https://github.com/MobileOrg/mobileorg/blob/develop/Configuration/AppKey.plist

**Comment by shaiguitar** [comment]
Hey @webframp, If you're on IRC/freenode or some place to chat I would be happy to catch up. I would still like to poke at this but I don't have much experience with xcode/iphone development and would likely need a bit of hand holding for the start.

**Comment by webframp** [comment]
Hi @shaiguitar I am occasionally around on irc and will get missed messages if you mention me there. Not sure I'm the best one for hand holding with iOS dev, but I can at least tell you what I do

**Comment by mgmart** [comment]
What's about a MobileOrg Community at Gitter? Wouldn't that serve the purpose best? Could try hand holding there -- irc does not work for me as I do not have a proper setup.

**Comment by webframp** [comment]
I'm ok with gitter, but haven't used it much. For irc I just use http://irccloud.com/ these days which is a nice setup

**Comment by shaiguitar** [comment]
In any case I think there are some basic-setup questions that make onboarding contributions to this repo a bit of a hurdle. Glad to help but I'll need someone to chat with to get started. I use this app a bunch and really do like it!

**Comment by mgmart** [comment]
Can you access Gitter? 
[![Gitter](https://img.shields.io/gitter/room/nwjs/nw.js.svg)](https://gitter.im/MobileOrg/Lobby)
There we could try to tackle the hurdles ;)

**Comment by mgmart** [comment]
Obtaining the keys is now documented in ReadMe.
