### ISSUE TITLE
Wrong year number in capture mode

### ISSUE THREAD

**Issue by junnik** [MobileOrg/mobileorg#77]
The time stamp on capture mode gets +1 year than actual. For example I create a notes on 2015-12-28 but mobileorg shows 2016-12-28 after saving notes.
This occurs only in year end (the last week of year?) as it was working fine weeks ago.

**Comment by mgmart** [comment]
Works for me at the moment. Seems we have to make some tests next week 🤓

**Comment by junnik** [comment]
Ok, will try and see what we get :-)

**Comment by mgmart** [comment]
Please reopen if anybody had still problems with year number last week.
