### ISSUE TITLE
iCloud support?

### ISSUE THREAD

**Issue by stig** [MobileOrg/mobileorg#78]
I would love to see iCloud Drive support! I don't use Dropbox but store my org files in iCloud Drive instead.

**Comment by watsy0007** [comment]
+1

**Comment by vermiculus** [comment]
@watsy0007 Please use GitHub's new reactions feature instead of commenting `+1` 😄

**Comment by webframp** [comment]
Thanks. It's on my list of stuff to do eventually. First priority is get an updated release out.

**Comment by mgmart** [comment]
Collected in Requirements
