### ISSUE TITLE
Support gpg files

### ISSUE THREAD

**Issue by shaiguitar** [MobileOrg/mobileorg#79]
I never really got passed #75 though I could be stumbling into n00b errors because I don't have much iphone/apple dev experience. Happy to try again but I'll likely need hand holding to get through the initial steps (for example via some slack/irc etc).

I have a `index.org` file that links to a bunch of other files, one of them being a gpg file. The other files open up in standard org row/line-items, but the gpg file is unresponsive. Is it possible to have mobile org support gpg?

**Comment by mgmart** [comment]
Collected in requirements
