### ISSUE TITLE
TODO items

### ISSUE THREAD

**Issue by notestaff** [MobileOrg/mobileorg#9]
In the original MobileOrg, TODO items could only be added in a flat list, and then had to be refiled.  It would be much better if you could add items in the proper place in their hierarchy.  Also be able to change item state, and have it sync with the corresponding item in the original file.  Maybe the git merge driver work from GSOC could be relevant here?

It would also be useful to be able to start and stop task timers on the phone i.e. the "tracking work time" feature of Org.

Thanks a lot!

ilya

**Comment by mgmart** [comment]
Is the first part of this ticket still true?
