### ISSUE TITLE
Looking for TestFlight volunteers for beta testing - v1.7.1

### ISSUE THREAD

**Issue by webframp** [MobileOrg/mobileorg#91]
There is active work to release a new, updated version of MobileOrg for iOS. The first beta of the new build has been submitted for Beta app review.

To help make it a high quality release I'm looking for additional volunteers to test the beta builds using TestFlight before we finally release. Volunteers who can test across a variety of devices would be preferred. 

If anyone is interested in helping out, please reply to this issue and provide the following details:

```md
## Your Name
## iOS Device model
## OS Version
## MobileOrg Sync Method
```

The first 3 people to respond will be added as external testers and then I'll try to select additional testers based on testing needs.

Once selected you can email me the icloud account email to use with testflight.

#### Status:
Current Testers from this thread: @jamie-conlon @thaaophz @stormlash @casserlyprogramming

**Comment by jamie-conlon** [comment]
Hey Sean 
I'd love to help.

Jamie
iPhone 6s
10.2
Dropbox

**Comment by casserlyprogramming** [comment]
Cool. Love org mode. Love MobileOrg 

Daniel
Iphone 7
10.2 when I have downloaded and installed it (today)
Dropbox

**Comment by tuxella** [comment]
I'd like to help you by testing this app:
Thomas
iPhone 6s
10.1.1
dropbox, but i have access to a caldav server if this helps

**Comment by thaaophz** [comment]
I'd like to help you by testing this app, too:

Matthias
iPhone 5
10.2
WebDav

**Comment by stormlash** [comment]
Sean,

I'm available too.

Peter Sahlstrom
iPhone 7+
10.1.1
WebDAV

**Comment by webframp** [comment]
Thanks for volunteering everyone. @casserlyprogramming @tuxella @thaaophz @stormlash can you email me your icloud ids and I'll add you to the external testers.

App hasn't passed beta review yet, but I'll send out the requests for testing as soon as it does

**Comment by fdhidalgo** [comment]
In case you are still looking for people, my stats are as follows:

Fernando Hidalgo
Iphone 6
10.2
Dropbox

**Comment by abradd** [comment]
Also available for testing if needed.

Adrian Bradd
iPhone 5s
10.2
Dropbox

**Comment by webframp** [comment]
Thanks for everyone who has volunteered so far, I have updated the issue with the names of those I've added so far. I think we have enough testers for now, but if needed I'll select others from this issue.

Just a brief note on the external testing, due to iTunes Connect policies:

> iTunes Connect Limited Availability: Dec 23-27
> New apps and app updates will not be accepted December 23 to 27 (Pacific Time)

I'm not sure how long it will take to pass the beta app review, but as soon as the bulid shows up and is available to enable for external testing I will update this issue.

**Comment by WilsonChiang** [comment]
Also available:

Wilson Chiang
iPhone 6s Plus
10.2
Dropbox

**Comment by webframp** [comment]
Just an updated for those who've been added as external testers. I've added a build to test but I'm still waiting for the Start Testing button to be available to me in iTunes connect external testing section. I'm assuming this means I'm still waiting on beta app review, but am not sure.

**Comment by alf** [comment]
Alf Lervåg
iPhone 6s
10.2.1 Beta 2
Dropbox

**Comment by mkasu** [comment]
Also available and interested, if you need any testers in future.

Marc
iPhone 6S Plus, iPad Air 2
10.2
WebDAV

**Comment by webframp** [comment]
Hey Everyone, thanks for volunteering. I have enough testers for now, but will look to add a few more eventually and will pull from this issue.

Invites went out for External testing of version 1.7.1 just now

**Comment by paulelms** [comment]
I can't believe that the MobileOrg is back, thanks to all!

Pavel (Paul)
iPhone 5 + Apple Watch, iPad Air 2
iOS public beta
WebDAV

**Comment by webframp** [comment]
@fdhidalgo @abradd @WilsonChiang @alf @mkasu and @paulelms If you send me your apple ids I will add you to the external testers list

**Comment by ckruse** [comment]
For how long is the test period planned? I'm eagerly awaiting a new release... ;-)

**Comment by webframp** [comment]
@ckruse depends on how many bugs are found and how much feedback we get 😁 
I don't expect it will need to go on much longer for the v1.7 release, it seems stable and we have fixed the few bugs we've been able to identify.

**Comment by michel-slm** [comment]
@webframp work issued me an iPhone and I've been missing MobileOrg ever since (1.6.1 Dropbox login seems broken) - if you could add me to the TestFlight beta that would be great!

Michel Alexandre Salim
iPhone 6s
iOS 10.2.1
Dropbox

**Comment by webframp** [comment]
@michel-slm ok send me your apple id.

Feedback from beta users would be much appreciated, so far it has been very limited.

**Comment by webframp** [comment]
Re-opening this issue until TestFlight testing is closed for beta v1.7.1

**Comment by therockmandolinist** [comment]
If this is still going on, count me in:

Diego A. Mundo
iPhone 5
iOS 10.2.1
Dropbox

**Comment by webframp** [comment]
@therockmandolinist will just need your apple id. I'll add you then you can use the beta and provide feedback and crash reports

**Comment by paulelms** [comment]
@webframp 
appleid: paul@elms.pro

**Comment by mgmart** [comment]
Sorry for hijacking this thread. But it's the only thread where I could get a notification to all beta-testers 🦄

We've started work on v2 and we need your input. 
The[ specification document](https://github.com/MobileOrg/mobileorg.next/blob/specification/docs/MobileOrgv2.org#software-architecture) evolves slowly and there are things we would [like to discuss].
(https://github.com/MobileOrg/mobileorg.next/labels/discussion) with you before taking decisions.

If you have any additional requirements feel free to add them as an issue or by pull request.

**Comment by jonathanwilner** [comment]
Jonathan Wilner
iPhone 7 Plus, iPad Pro 12.9, IPhone 6 Plus, Apple Watch Series 1
iOS 10.2.1, WatchOS 3.1.3
Dropbox

**Comment by dnesbitt03qub** [comment]
David
iPhone 7
10.2.1
Dropbox

**Comment by webframp** [comment]
Closing this issue now since v1.7.1 has been sent for review. Thanks beta testers.

@jonathanwilner @dnesbitt03qub since you just posted, just send me your apple ids if you want and I'll add you in for the next round of testing whenever it is needed.
