### ISSUE TITLE
Make use of WebDav in unit tests

### ISSUE THREAD

**Issue by mgmart** [MobileOrg/mobileorg#95]
As a developer I would like to use WebDav in unit tests.

Provide a framework which allows the use of WebDav in unit tests.
This could be done by using a [WebDav Test Server](http://test.webdav.org)

**Comment by webframp** [comment]
#133 and #134 kind of shine a light on the need for this

**Comment by mgmart** [comment]
It seems we've done our manual tests with Dropbox only.
This might help to prevent that in the future: https://itunes.apple.com/de/app/webdavnav-server/id747482894?mt=12

**Comment by mgmart** [comment]
#185 is the next issue which could have been prevented if there would be proper unit tests for WebDAV.

Best approach seems to be using a [docker repo](https://hub.docker.com/r/phylor/webdav-ssl/) which can be configured with trusted self signed and 'real' certificates.

**Comment by mgmart** [comment]
WebDAV Server using docker was added.
https://github.com/MobileOrg/mobileorg/pull/186/commits/83b74dfbdf2ba657ac0017eb9d5ed5a2fe4994ea
