### ISSUE TITLE
MobileOrg icon and launch screen poll

### ISSUE THREAD

**Issue by d12frosted** [MobileOrg/mobileorg#98]
Hey folks,

Recently we have [updated](https://github.com/MobileOrg/mobileorg/commit/268a507a010fd2f260e2252aa0480cc7547fd7f1) launch screen image with a fancy org-mode icon. Since it's not in the same as application icon @webframp suggested to use the same icon in both places. So let's vote for the icon you, MobileOrg users, prefer. 

# Original icon

![](https://raw.githubusercontent.com/MobileOrg/mobileorg.github.io/develop/source/img/org-mode-unicorn-logo-large.png)

# Modern (new) icon

![](https://raw.githubusercontent.com/MobileOrg/mobileorg/develop/MobileOrg/Images.xcassets/IOrgIcon.imageset/org-mode-icon%403x.png)

# Voting

In order to avoid spam to the inboxes of project watchers, let's vote using GitHub reaction feature on PRs. Let's agree that 👍 is for using modern icon and 👎 is for leaving an old version. +/- were chosen without any additional meaning and without any intention to offend anyone. 

P. S. You are still free to discuss this issue, so don't hesitate to share any thoughts you have on this topic.

**Comment by webframp** [comment]
For reference: [Apple HIG - App Icon](https://developer.apple.com/ios/human-interface-guidelines/graphics/app-icon/)

**Comment by mgmart** [comment]
Should we close this poll in a week from now?

**Comment by webframp** [comment]
One more week seems sufficient to me

**Comment by d12frosted** [comment]
Modern icon has won. I'll send a PR on this weekends with an update.

**Comment by mgmart** [comment]
Which would contain the launch screen?
App icons would then be another task?

**Comment by jamie-conlon** [comment]
Wait... Are the images mixed up under the headings? Is the new image the simpler looking one?

**Comment by mgmart** [comment]
I suppose they are. But the vote results are gathered according to the writing here. Which means the second icon with the friendlier looking unicorn has won.

I hope that is ok for everyone.

**Comment by d12frosted** [comment]
Sorry for misunderstanding. From my point of view the second one is new 😸 

P. S. We should also change organisation icon as well.

**Comment by d12frosted** [comment]
Started to work on it here: https://github.com/MobileOrg/mobileorg/pull/132

Note that launch screen is already updated.

P. S. Closing this as the poll is over. Reopen if you wish to have it open 😸

**Comment by webframp** [comment]
@d12frosted changed github org logo to match

**Comment by d12frosted** [comment]
@webframp many thanks!
